### ISSUE TITLE
Fix type declaration

### ISSUE THREAD

**Issue by DannyFeliz** [DannyFeliz/vue-tweet#1]
Currently, we are not getting any hint while passing prop to the component

**Comment by Boluwatife2904** [comment]
Good afternoon @DannyFeliz I just sent You a DM on Twitter as regards using this awesome package via a CDN link which I could not find on the documentation. I would be grateful if You could point me in the right directions. Looking forward to your reply. Thanks.

**Comment by DannyFeliz** [comment]
@Boluwatife2904, sorry for the late response, I updated this package and fixed all the issues related to the differents builds, you should be able to use it as a CDN like this

You can use it like this: <script type="application/javascript" src="https://unpkg.com/vue-tweet"></script>

**Comment by Boluwatife2904** [comment]
Thanks a lot for this🙌🏽🙌🏽🙌🏽. Checking it out.
