### ISSUE TITLE
Multiple widget.js script import 

### ISSUE THREAD

**Issue by mahapo** [DannyFeliz/vue-tweet#2]
If I use multiple tweets, it adds for each tweet a widgets.js to the DOM
<img width="952" alt="image" src="https://user-images.githubusercontent.com/28730855/171384058-90de30b3-920b-4a3f-aac1-b84af1bf885c.png">

**Comment by DannyFeliz** [comment]
Thanks for the report, it's fixed on this PR https://github.com/DannyFeliz/vue-tweet/pull/28
