### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'isCE')

### ISSUE THREAD

**Issue by sharon-alexander** [DannyFeliz/vue-tweet#29]
I was using your package and it was working perfectly until a few days ago. I am getting this error even though the tweet ID passed to the component is a valid string of an id. 
<img width="408" alt="Screenshot 2024-04-29 at 10 18 50 AM" src="https://github.com/DannyFeliz/vue-tweet/assets/66204052/46d5f119-0f4f-4ee4-9316-aea7a2368a7a">

**Comment by alectrocute** [comment]
@DannyFeliz Also running into this. Any ideas?

**Comment by DannyFeliz** [comment]
Sorry for the late response; I will take a look this weekend.

**Comment by MariusRumpf** [comment]
Same issue, any release after 2.0.2 seems to contain a bundled version of vue. This causes an issue when running multiple version of vue. A downgrade fixed the issue.

**Comment by DannyFeliz** [comment]
That was a long weekend 😄 . Sorry for the delay; this is fixed now in the latest version; please install version 2.2.5.
