### ISSUE TITLE
Neither tweet-load-success or tweet-load-error are firing

### ISSUE THREAD

**Issue by Majncz** [DannyFeliz/vue-tweet#30]
I may be dumb and it's my mistake, but even tho the posts do load, nothing gets logged in console.
Slots do work, only this doesn't.

```html
<Tweet v-for="(postId, index) in postIds.filter((_, index) => index % 2 !== 0)" :key="postId"
  :tweet-id="postId" :width="'100%'" :dnt="true"
  @tweet-load-success="() => console.log('tweet loaded')"
  @tweet-load-error="() => console.log('tweet error')" />
```

Thanks ahead for looking into this.

**Comment by DannyFeliz** [comment]
Hi @Majncz, I tried your example and it works fine:
```vue
<script setup lang="ts">
import Tweet from "vue-tweet";
</script>

<template>
  <Tweet
    tweet-id="1832531798170976659"
    @tweet-load-success="() => console.log('tweet loaded')"
    @tweet-load-error="() => console.log('tweet error')"
  />
</template>

```

You can try it in [codesanbox](https://codesandbox.io/p/devbox/3t4ltl?embed=1&showConsole=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0snfspf00073b6nxw40xv9o%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0snfspe00023b6nbiumew1m%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0snfspe00043b6njq1hari9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0snfspe00063b6nyvog0mfr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0snfspe00023b6nbiumew1m%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0snfspe00013b6nim7w4z7j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm0snvk6p00023b6kkclyvcik%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0snfspe00023b6nbiumew1m%2522%252C%2522activeTabId%2522%253A%2522cm0snvk6p00023b6kkclyvcik%2522%257D%252C%2522cm0snfspe00063b6nyvog0mfr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0snfspe00053b6np2l7b9fb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cm0snfspe00063b6nyvog0mfr%2522%252C%2522activeTabId%2522%253A%2522cm0snfspe00053b6np2l7b9fb%2522%257D%252C%2522cm0snfspe00043b6njq1hari9%2522%253A%257B%2522id%2522%253A%2522cm0snfspe00043b6njq1hari9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0snfspe00033b6nm562zarc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cm0snfspe00033b6nm562zarc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) and open the codesanbox devtools and you will see the logs there.

**Comment by Majncz** [comment]
Alright, suddenly it started working, I swear, yesterday it wasn't 😅😂
Sorry for wasting your time
